server:
  address: localhost
  port: 18081

spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: token1234
      jdbcUrl: jdbc:mysql://forlks.cbbo5nrygkst.us-east-2.rds.amazonaws.com:3306/tokendbmaster?useSSL=false&characterEncoding=UTF-8
      username: tokenuser
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: token1234
      jdbcUrl: jdbc:mysql://forlks.cbbo5nrygkst.us-east-2.rds.amazonaws.com:3306/tokendbslave?useSSL=false&characterEncoding=UTF-8
      username: tokenuser
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true